services:
  - mysql

language: "perl"
perl:
  - "5.20"

before_install:
  - cpanm -q --notest install Sparrow

install:
  - sparrow index update
  - sparrow plg install mysql-check

script:
  - sparrow plg run mysql-check
